### ISSUE TITLE
Installation Fails on Current Ruby and Current Redmine 3

### ISSUE THREAD

**Issue by frank-dspeed** [DIREKTSPEED-LTD/ds-redmine_backlogs#1]
Waiting for database server to accept connections
Installing plugins...
Installing gems required by plugins...
Don't run Bundler as root. Bundler can ask for sudo if it is needed, and
installing your bundle as root will break this application for all non-root
users on this machine.
Warning: this Gemfile contains multiple primary sources. Using `source` more than once without a block is a security risk, and may result in installing unexpected gems. To resolve this warning, use a block to indicate which gems should come from the secondary source. To upgrade this warning to an error, run `bundle config disable_multisource true`.
Fetching gem metadata from https://rubygems.org/.......
Fetching version metadata from https://rubygems.org/..
Resolving dependencies...
Using rake 10.4.2
Using i18n 0.7.0
Using json 1.8.2
Using minitest 5.5.1
Using thread_safe 0.3.4
Using tzinfo 1.2.2
Using activesupport 4.2.0
Using builder 3.2.2
Using erubis 2.7.0
Using mini_portile 0.6.2
Using nokogiri 1.6.6.2
Using rails-deprecated_sanitizer 1.0.3
Using rails-dom-testing 1.0.5
Using loofah 2.0.1
Using rails-html-sanitizer 1.0.1
Using actionview 4.2.0
Using rack 1.6.0
Using rack-test 0.6.3
Using actionpack 4.2.0
Using globalid 0.3.3
Using activejob 4.2.0
Using mime-types 2.4.3
Using mail 2.6.3
Using actionmailer 4.2.0
Using actionpack-action_caching 1.1.1
Using actionpack-xml_parser 1.0.1
Using activemodel 4.2.0
Using arel 6.0.0
Using activerecord 4.2.0
Using bundler 1.8.3
Using xpath 2.0.0
Using capybara 2.4.4
Using ffi 1.9.6
Using childprocess 0.5.5
Using coderay 1.1.0
Installing daemons 1.2.2
Using dalli 2.7.2
Using docile 1.1.5
[root@ovh2 plugins]# docker logs projects.dspeed.eu
Waiting for database server to accept connections
Installing plugins...
Installing gems required by plugins...
Don't run Bundler as root. Bundler can ask for sudo if it is needed, and
installing your bundle as root will break this application for all non-root
users on this machine.
Warning: this Gemfile contains multiple primary sources. Using `source` more than once without a block is a security risk, and may result in installing unexpected gems. To resolve this warning, use a block to indicate which gems should come from the secondary source. To upgrade this warning to an error, run `bundle config disable_multisource true`.
Fetching gem metadata from https://rubygems.org/.......
Fetching version metadata from https://rubygems.org/..
Resolving dependencies...
Using rake 10.4.2
Using i18n 0.7.0
Using json 1.8.2
Using minitest 5.5.1
Using thread_safe 0.3.4
Using tzinfo 1.2.2
Using activesupport 4.2.0
Using builder 3.2.2
Using erubis 2.7.0
Using mini_portile 0.6.2
Using nokogiri 1.6.6.2
Using rails-deprecated_sanitizer 1.0.3
Using rails-dom-testing 1.0.5
Using loofah 2.0.1
Using rails-html-sanitizer 1.0.1
Using actionview 4.2.0
Using rack 1.6.0
Using rack-test 0.6.3
Using actionpack 4.2.0
Using globalid 0.3.3
Using activejob 4.2.0
Using mime-types 2.4.3
Using mail 2.6.3
Using actionmailer 4.2.0
Using actionpack-action_caching 1.1.1
Using actionpack-xml_parser 1.0.1
Using activemodel 4.2.0
Using arel 6.0.0
Using activerecord 4.2.0
Using bundler 1.8.3
Using xpath 2.0.0
Using capybara 2.4.4
Using ffi 1.9.6
Using childprocess 0.5.5
Using coderay 1.1.0
Installing daemons 1.2.2
Using dalli 2.7.2
Using docile 1.1.5
Installing eventmachine 1.0.7
Using hike 1.2.3
Installing holidays 1.0.8
Installing icalendar 2.2.2
Using thor 0.19.1
Using railties 4.2.0
Using jquery-rails 3.1.2
Using kgio 2.9.3
Using metaclass 0.0.4
Using mocha 1.1.0
Using multi_json 1.10.1
Using mysql2 0.3.18
Using net-ldap 0.3.1
Installing open-uri-cached 0.0.5
Installing pdf-core 0.5.1
Using pg 0.17.1
Installing ttfunk 1.4.0
Installing prawn 2.0.1
Using protected_attributes 1.0.8
Using ruby-openid 2.3.0
Using rack-openid 1.4.2
Using tilt 1.4.1
Using sprockets 2.12.3
Using sprockets-rails 2.2.4
Using rails 4.2.0
Using raindrops 0.13.0
Using rbpdf 1.18.5
Using redcarpet 3.1.2
Using request_store 1.0.5
Using rmagick 2.13.4
Using rubyzip 1.1.7
Using websocket 1.2.1
Using selenium-webdriver 2.45.0
Using simplecov-html 0.9.0
Using simplecov 0.9.2
Installing thin 1.6.3
Using unicorn 4.8.3
Bundle complete! 38 Gemfile dependencies, 75 gems now installed.
Gems in the groups development and tests were not installed.
Bundled gems are installed into ./vendor/bundle.
Post-install message from icalendar:
HEADS UP! iCalendar 2.0 is not backwards-compatible with 1.x. Please see the README for the new syntax

HEADS UP! icalendar 2.2.0 switches to non-strict parsing as default. Please see the README if you
rely on strict parsing for information on how to enable it.

ActiveSupport is required for TimeWithZone support, but not required for general use.
Migrating plugins. Please be patient, this could take a while...
rake aborted!
ArgumentError: The scope body needs to be callable.
/home/redmine/redmine/vendor/bundle/ruby/2.1.0/gems/activerecord-4.2.0/lib/active_record/scoping/named.rb:143:in `scope'
/home/redmine/redmine/plugins/redmine_backlogs/app/models/rb_release.rb:174:in`class:RbRelease'
/home/redmine/redmine/plugins/redmine_backlogs/app/models/rb_release.rb:156:in `<top (required)>'
/home/redmine/redmine/vendor/bundle/ruby/2.1.0/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:274:in`require'
/home/redmine/redmine/vendor/bundle/ruby/2.1.0/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:274:in `block in require'
/home/redmine/redmine/vendor/bundle/ruby/2.1.0/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:240:in`load_dependency'
/home/redmine/redmine/vendor/bundle/ruby/2.1.0/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:274:in `require'
/home/redmine/redmine/vendor/bundle/ruby/2.1.0/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:360:in`require_or_load'
/home/redmine/redmine/vendor/bundle/ruby/2.1.0/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:494:in `load_missing_constant'
/home/redmine/redmine/vendor/bundle/ruby/2.1.0/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:184:in`const_missing'
/home/redmine/redmine/vendor/bundle/ruby/2.1.0/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:526:in `load_missing_constant'
/home/redmine/redmine/vendor/bundle/ruby/2.1.0/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:184:in`const_missing'
/home/redmine/redmine/vendor/bundle/ruby/2.1.0/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:526:in `load_missing_constant'
/home/redmine/redmine/vendor/bundle/ruby/2.1.0/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:184:in`const_missing'
/home/redmine/redmine/plugins/redmine_backlogs/lib/backlogs_project_patch.rb:176:in `block in included'
/home/redmine/redmine/plugins/redmine_backlogs/lib/backlogs_project_patch.rb:174:in`class_eval'
/home/redmine/redmine/plugins/redmine_backlogs/lib/backlogs_project_patch.rb:174:in `included'
/home/redmine/redmine/plugins/redmine_backlogs/lib/backlogs_project_patch.rb:346:in`include'
/home/redmine/redmine/plugins/redmine_backlogs/lib/backlogs_project_patch.rb:346:in `<top (required)>'
/home/redmine/redmine/vendor/bundle/ruby/2.1.0/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:274:in`require'
/home/redmine/redmine/vendor/bundle/ruby/2.1.0/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:274:in `block in require'
/home/redmine/redmine/vendor/bundle/ruby/2.1.0/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:240:in`load_dependency'
/home/redmine/redmine/vendor/bundle/ruby/2.1.0/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:274:in `require'
/home/redmine/redmine/vendor/bundle/ruby/2.1.0/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:360:in`require_or_load'
/home/redmine/redmine/vendor/bundle/ruby/2.1.0/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:317:in `depend_on'
/home/redmine/redmine/vendor/bundle/ruby/2.1.0/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:233:in`require_dependency'
/home/redmine/redmine/plugins/redmine_backlogs/init.rb:32:in `block in <top (required)>'
/home/redmine/redmine/vendor/bundle/ruby/2.1.0/gems/activesupport-4.2.0/lib/active_support/callbacks.rb:441:in`instance_exec'
/home/redmine/redmine/vendor/bundle/ruby/2.1.0/gems/activesupport-4.2.0/lib/active_support/callbacks.rb:441:in `block in make_lambda'
/home/redmine/redmine/vendor/bundle/ruby/2.1.0/gems/activesupport-4.2.0/lib/active_support/callbacks.rb:189:in`call'
/home/redmine/redmine/vendor/bundle/ruby/2.1.0/gems/activesupport-4.2.0/lib/active_support/callbacks.rb:189:in `block in simple'
/home/redmine/redmine/vendor/bundle/ruby/2.1.0/gems/activesupport-4.2.0/lib/active_support/callbacks.rb:190:in`call'
/home/redmine/redmine/vendor/bundle/ruby/2.1.0/gems/activesupport-4.2.0/lib/active_support/callbacks.rb:190:in `block in simple'
/home/redmine/redmine/vendor/bundle/ruby/2.1.0/gems/activesupport-4.2.0/lib/active_support/callbacks.rb:92:in`call'
/home/redmine/redmine/vendor/bundle/ruby/2.1.0/gems/activesupport-4.2.0/lib/active_support/callbacks.rb:92:in `_run_callbacks'
/home/redmine/redmine/vendor/bundle/ruby/2.1.0/gems/activesupport-4.2.0/lib/active_support/callbacks.rb:734:in`_run_prepare_callbacks'
/home/redmine/redmine/vendor/bundle/ruby/2.1.0/gems/activesupport-4.2.0/lib/active_support/callbacks.rb:81:in `run_callbacks'
/home/redmine/redmine/vendor/bundle/ruby/2.1.0/gems/actionpack-4.2.0/lib/action_dispatch/middleware/reloader.rb:83:in`prepare!'
/home/redmine/redmine/vendor/bundle/ruby/2.1.0/gems/actionpack-4.2.0/lib/action_dispatch/middleware/reloader.rb:55:in `prepare!'
/home/redmine/redmine/vendor/bundle/ruby/2.1.0/gems/railties-4.2.0/lib/rails/application/finisher.rb:50:in`block in module:Finisher'
/home/redmine/redmine/vendor/bundle/ruby/2.1.0/gems/railties-4.2.0/lib/rails/initializable.rb:30:in `instance_exec'
/home/redmine/redmine/vendor/bundle/ruby/2.1.0/gems/railties-4.2.0/lib/rails/initializable.rb:30:in`run'
/home/redmine/redmine/vendor/bundle/ruby/2.1.0/gems/railties-4.2.0/lib/rails/initializable.rb:55:in `block in run_initializers'
/home/redmine/redmine/vendor/bundle/ruby/2.1.0/gems/railties-4.2.0/lib/rails/initializable.rb:54:in`run_initializers'
/home/redmine/redmine/vendor/bundle/ruby/2.1.0/gems/railties-4.2.0/lib/rails/application.rb:352:in `initialize!'
/home/redmine/redmine/config/environment.rb:14:in`<top (required)>'
/home/redmine/redmine/vendor/bundle/ruby/2.1.0/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:274:in `require'
/home/redmine/redmine/vendor/bundle/ruby/2.1.0/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:274:in`block in require'
/home/redmine/redmine/vendor/bundle/ruby/2.1.0/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:240:in `load_dependency'
/home/redmine/redmine/vendor/bundle/ruby/2.1.0/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:274:in`require'
/home/redmine/redmine/vendor/bundle/ruby/2.1.0/gems/railties-4.2.0/lib/rails/application.rb:328:in `require_environment!'
/home/redmine/redmine/vendor/bundle/ruby/2.1.0/gems/railties-4.2.0/lib/rails/application.rb:443:in`block in run_tasks_blocks'
Tasks: TOP => redmine:plugins:migrate => environment

**Comment by vietvuhoang** [comment]
Hi, do you have any feedback from this error? 
Do you have any solution? I got same problem with it.

**Comment by frank-dspeed** [comment]
No news about that :( but i think this backlogs plugin is even not worth fixing it Our Company is at present porting redmine functionality to NODE.JS because the code base is in my eyes totall bloated

**Comment by vietvuhoang** [comment]
I think because of Redmine 3 framework is changed. Backlog just supports Redmine 2.
